version: '3.7'

services:
  wordpress: &wordpress
    build: &build
      context: .
    ports:
      - 8080:80
    depends_on:
      - db
    volumes:
      - /var/www/html
      - ./woocommerce-begateway:/var/www/html/wp-content/plugins/woocommerce-begateway
      - ./docker/src/languages:/var/www/html/wp-content/languages
    restart: always
    networks:
      - default
    environment:
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_HOST: db

  woocommerce_3:
    build:
      args:
        wc_version: "3.7.1"
      <<: *build
    <<: *wordpress

  woocommerce_4:
    build:
      args:
        wc_version: "4.0.1"
      <<: *build
    <<: *wordpress

  db:
    image: mysql:5.7
    restart: always
    networks:
      - default
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
